### ISSUE TITLE
Add New Shapes - Template/Guide?

### ISSUE THREAD

**Issue by terencelim** [bitbof/webchemy#1]
hi bitbof, how do you add/create new shape paths? Is there an SVG template or guide on how to do this? Thanks

**Comment by bitbof** [comment]
Hey. Within the function `WebchemyBrush`there are two arrays of pull shapes, `shapes` and `shapesAlt` (when "Splat" is on). If you change those or add new shapes to these arrays they will show up as you draw.

Each shape is simply a SVG path (https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#path_commands). Not all draw commands are supported (see `LIB.drawPathOnCanvas`). 
The way it looks the paths need to be already transformed to fit between -100 to 100.

I think I authored the paths in Inkscape. Then simply copied the value of `d` from the saved SVG file.
